wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.2
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 10
fc1:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.005
weight_decay:
  desc: null
  value: 0.001
